runtime: nodejs16

instance_class: F2

handlers:
  - url: /images
    static_dir: public/images
  - url: /javascripts
    static_dir: public/javascripts
  - url: /stylesheets
    static_dir: public/stylesheets

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
